import type { ThemeConfig } from './types';

export function generateThemeCss(theme: ThemeConfig): string {
  const lines: string[] = [];

  // Colors
  if (theme.colors) {
    Object.entries(theme.colors).forEach(([key, value]) => {
      if (typeof value === 'string') {
        lines.push(`  --color-${key}: ${value};`);
      } else if (typeof value === 'object' && value !== null) {
        if ('DEFAULT' in value) {
          lines.push(`  --color-${key}: ${value.DEFAULT};`);
        }
        if ('foreground' in value) {
          lines.push(
            `  --color-${key}-foreground: ${value.foreground};`,
          );
        }
      }
    });
  }

  // Radius
  if (theme.radius) {
    Object.entries(theme.radius).forEach(([key, value]) => {
      lines.push(`  --radius-${key}: ${value};`);
    });
  }

  // Font sizes
  if (theme.fontSize) {
    Object.entries(theme.fontSize).forEach(([key, value]) => {
      if (Array.isArray(value)) {
        const [size, config] = value;
        lines.push(`  --text-${key}: ${size};`);
        if (config.lineHeight) {
          lines.push(`  --leading-${key}: ${config.lineHeight};`);
        }
      } else {
        lines.push(`  --text-${key}: ${value};`);
      }
    });
  }

  // Font families
  if (theme.fontFamily) {
    Object.entries(theme.fontFamily).forEach(([key, value]) => {
      lines.push(`  --font-${key}: ${value.join(', ')};`);
    });
  }

  // Font weights
  if (theme.fontWeight) {
    Object.entries(theme.fontWeight).forEach(([key, value]) => {
      lines.push(`  --font-weight-${key}: ${value};`);
    });
  }

  // Shadows
  if (theme.shadows) {
    Object.entries(theme.shadows).forEach(([key, value]) => {
      lines.push(`  --shadow-${key}: ${value};`);
    });
  }

  // Z-index
  if (theme.zIndex) {
    Object.entries(theme.zIndex).forEach(([key, value]) => {
      lines.push(`  --z-${key}: ${value};`);
    });
  }

  // Animation
  if (theme.animation) {
    if (theme.animation.duration) {
      Object.entries(theme.animation.duration).forEach(
        ([key, value]) => {
          lines.push(`  --duration-${key}: ${value};`);
        },
      );
    }
    if (theme.animation.ease) {
      Object.entries(theme.animation.ease).forEach(([key, value]) => {
        lines.push(`  --ease-${key}: ${value};`);
      });
    }
  }

  return lines.join('\n');
}

export interface CustomTheme {
  name: string;
  className: string;
  config: ThemeConfig;
  description?: string;
}

export function generateThemeFile(
  lightTheme: ThemeConfig,
  darkTheme: ThemeConfig,
  customThemes: CustomTheme[] = [],
): string {
  const customThemesSection =
    customThemes.length > 0
      ? `\n/* ==================== Custom Brand Themes ==================== */\n\n${customThemes
          .map(
            (theme) => `/**
 * ${theme.name}${theme.description ? ` - ${theme.description}` : ''}
 * Usage: <html class="${theme.className}">
 */
.${theme.className} {
${generateThemeCss(theme.config)}
}`,
          )
          .join('\n\n')}`
      : '';

  const sourceFiles = [
    'Light: packages/ui/src/theme/tokens/presets/default.ts',
    'Dark: packages/ui/src/theme/tokens/presets/default-dark.ts',
    ...customThemes.map(
      (theme) =>
        `${theme.name}: packages/ui/src/theme/tokens/presets/${theme.className.replace('theme-', '')}.ts`,
    ),
  ]
    .map((line) => ` * - ${line}`)
    .join('\n');

  return `/**
 * Design Token System - Auto-generated CSS
 *
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 * [파일을 수동으로 편집하지 마세요]
 * This file is automatically generated from TypeScript theme presets
 * [TypeScript 테마 프리셋에서 이 파일이 자동으로 생성됩니다]
 * Source files:
${sourceFiles}
 *
 * To regenerate: pnpm generate:theme
 * Last generated: ${new Date().toISOString()}
 */

@import 'tailwindcss';

/* ==================== Light Mode (Default) ==================== */

@theme {
${generateThemeCss(lightTheme)}
}

/* ==================== Dark Mode ==================== */

.dark {
${generateThemeCss(darkTheme)}
}${customThemesSection}
`;
}
